"""add_name

Revision ID: 17b183a7e05e
Revises: f87bbdd0e7e6
Create Date: 2024-05-23 08:07:29.901445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b183a7e05e'
down_revision: Union[str, None] = 'f87bbdd0e7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'persentOfIncome',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('stores', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('stores', 'address')
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('user', 'FIO')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('FIO', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    op.add_column('stores', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('stores', 'name')
    op.alter_column('product', 'persentOfIncome',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
