"""db

Revision ID: 3ff11b0b4e76
Revises: 41ac7547f07b
Create Date: 2024-05-25 00:23:02.926970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff11b0b4e76'
down_revision: Union[str, None] = '41ac7547f07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category')
    op.drop_column('product', 'persentOfIncome')
    op.drop_column('product', 'totalPersentOfIncome')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('totalPersentOfIncome', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('persentOfIncome', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('category', postgresql.ENUM('A', 'B', 'C', name='categoryofproduct'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
