"""db

Revision ID: 41ac7547f07b
Revises: 17b183a7e05e
Create Date: 2024-05-23 22:49:03.223794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ac7547f07b'
down_revision: Union[str, None] = '17b183a7e05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'general_amount_of_products')
    op.drop_column('company', 'general_amount_of_products_on_stores')
    op.add_column('product', sa.Column('totalPersentOfIncome', sa.Float(precision=2), nullable=True))
    op.alter_column('product', 'persentOfIncome',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'persentOfIncome',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('product', 'totalPersentOfIncome')
    op.add_column('company', sa.Column('general_amount_of_products_on_stores', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('general_amount_of_products', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
