"""status_del

Revision ID: 9493d531458c
Revises: b63264e034c4
Create Date: 2024-05-29 15:55:00.112147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9493d531458c'
down_revision: Union[str, None] = 'b63264e034c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('displacement', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('displacement', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
