"""status_del

Revision ID: a38f75dc26fc
Revises: 9493d531458c
Create Date: 2024-05-31 01:39:38.016810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38f75dc26fc'
down_revision: Union[str, None] = '9493d531458c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'predictCount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('predictCount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
