"""operations_del

Revision ID: b63264e034c4
Revises: 3ff11b0b4e76
Create Date: 2024-05-28 16:26:48.539608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63264e034c4'
down_revision: Union[str, None] = '3ff11b0b4e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('infoAboutInventory')
    op.add_column('return', sa.Column('cost', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return', 'cost')
    op.create_table('infoAboutInventory',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"infoAboutInventory_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('idProduct', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idInventory', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expectedAmount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amountAtFact', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idInventory'], ['product.id'], name='infoAboutInventory_idInventory_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idProduct'], ['product.id'], name='infoAboutInventory_idProduct_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='infoAboutInventory_pkey')
    )
    op.create_table('inventory',
    sa.Column('idStore', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idCompany', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idWorker', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idCompany'], ['company.id'], name='inventory_idCompany_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idStore'], ['stores.id'], name='inventory_idStore_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idWorker'], ['user.id'], name='inventory_idWorker_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey')
    )
    # ### end Alembic commands ###
