"""defaulte

Revision ID: f6dd3e2ccceb
Revises: 226085b8649a
Create Date: 2024-05-22 00:46:36.315210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dd3e2ccceb'
down_revision: Union[str, None] = '226085b8649a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'predictCount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'persentOfIncome',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'persentOfIncome',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('product', 'predictCount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
